### ISSUE TITLE
`cargo install blendr` fails compiling `blendr` crate

### ISSUE THREAD

**Issue by develop7** [dmtrKovalenko/blendr#12]
Repro:

1. Run `cargo install blendr`

Expected: `blendr` installs

Instead: `blendr` compilation fails with following error

<details>
<summary>Details</summary>

```
error[E0271]: type mismatch resolving `<IntoIter<Line<'_>> as IntoIterator>::Item == Line<'_>`
   --> /home/adziahel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blendr-1.1.1/src/tui/connection_view.rs:292:29
    |
292 |                 text.extend(output.into_iter());
    |                      ------ ^^^^^^^^^^^^^^^^^^ expected `ratatui::text::Line<'_>`, found `ratatui::text::line::Line<'_>`
    |                      |
    |                      required by a bound introduced by this call
    |
    = note: `ratatui::text::line::Line<'_>` and `ratatui::text::Line<'_>` have similar names, but are actually distinct types
note: `ratatui::text::line::Line<'_>` is defined in crate `ratatui`
   --> /home/adziahel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.22.0/src/text/line.rs:8:1
    |
8   | pub struct Line<'a> {
    | ^^^^^^^^^^^^^^^^^^^
note: `ratatui::text::Line<'_>` is defined in crate `ratatui`
   --> /home/adziahel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.21.0/src/text/line.rs:6:1
    |
6   | pub struct Line<'a> {
    | ^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `ratatui` are being used?
note: the method call chain might not have had the expected associated types
   --> /home/adziahel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/blendr-1.1.1/src/tui/connection_view.rs:292:36
    |
292 |                 text.extend(output.into_iter());
    |                             ------ ^^^^^^^^^^^ `IntoIterator::Item` is `Line<'_>` here
    |                             |
    |                             this expression has type `Text<'_>`
note: required by a bound in `extend`
   --> /home/adziahel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/collect.rs:377:31
    |
377 |     fn extend<T: IntoIterator<Item = A>>(&mut self, iter: T);
    |                               ^^^^^^^^ required by this bound in `Extend::extend`

For more information about this error, try `rustc --explain E0271`.
error: could not compile `blendr` (bin "blendr") due to previous error
error: failed to compile `blendr v1.1.1`, intermediate artifacts can be found at `/tmp/cargo-installb8EvBv`
```

</details>

**Comment by arindamchoudhury** [comment]
I have encountered the same problem

**Comment by ScripterSugar** [comment]
Having exact same problem too!

**Comment by dmtrKovalenko** [comment]
How is that possible that I missed this issue 😨

**Comment by develop7** [comment]
> How is that possible that I missed this issue 😨

Well? 🥺

**Comment by dmtrKovalenko** [comment]
Please use the binary installation for now, it will work. I'll do my best to resolve this issue in the next 24 hours

**Comment by dmtrKovalenko** [comment]
After some investigations appears that the real reason of this issue comes form cargo and not from us. TLDR by default cargo install is not using Cargo.lock for binary dependencies and tries to install the latest version of all dependencies available. 

And we have specific conflict with ratatui 0.22.0 which throws this error. Solution: use --locked arg:

```
cargo install blendr --locked
```

**Comment by pavlus** [comment]
The issue is still present, and the solution no longer works, as
```sh
cargo install blendr --locked
``
fails with:
```
   ...
   Compiling libdbus-sys v0.2.5
error[E0282]: type annotations needed for `Box<_>`
  --> /home/pavel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.22/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `blendr v1.3.3`, intermediate artifacts can be found at `/tmp/cargo-installQ3d0mU`.
```
